version: '2'

services:

  wordpress-mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./data/mysql:/var/lib/mysql

  wordpress-web:
    build: .
    image: wordpress-web
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_PASSWORD: my-secret-pw
    working_dir: /var/www/html
    volumes:
      - ./data/wordpress/wp-content:/var/www/html/wp-content
    links:
      - wordpress-mariadb:mysql
